apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io

# operation:
#   sync:
#     synStrategy:
#       apply:
#         force: true
spec:
  # ignoreDifferences:
  # - group: '*'
  #   kind: Application
  #   jsonPointers:
  #   - /operation
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'
  project: default
  source:
    path: test-app/
    repoURL: https://github.com/d-cryptic/testing-argocd-2.git
    targetRevision: HEAD
    directory:
      recurse: true
      # exclude: '{config.json}'
      # include: '*.yaml'
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Prune=true
      - PrunePropagationPolicy=orphan
      - Delete=true