apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: root-app
  namespace: argocd
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    name: in-cluster
  project: default
  source:
    path: test-app/
    repoURL: https://github.com/d-cryptic/testing-argocd-2.git
    targetRevision: HEAD
    directory:
      recurse: true
      exclude: '{config.json}'
      include: '*.yaml'
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
      - CreateNamespace=true